version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    networks:
      - myNetwork
    volumes:
      - ./.env:/opt/app/.env
    container_name: api
    depends_on:
      - rmq
  rmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
      - myNetwork
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    networks:
      - myNetwork
    container_name: app
  converter:
    build:
      context: .
      dockerfile: ./apps/converter/Dockerfile
    restart: always
    container_name: converter
    networks:
      - myNetwork
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - rmq
networks:
  myNetwork:
    driver: bridge
